### ISSUE TITLE
Documentation Roadmap

### ISSUE THREAD

**Issue by aevitas** [fern-api/fern#1872]
Tracking issue for documentation improvements.

Goals:
* Provide a better onboarding experience for new users for all stages of REST API development using fern (design, build, document)
* Document generator infrastructure and architecture
* Document the generation of documentation by Fern
* Move Fern's own docs to its own repository
* Move Fern's own docs to the Fern documentation generation ecosystem

- [x] fern-api/fern README overhaul - (#1832)
- [x] Generator READMEs (#1870)
- [x] Move [Fern documentation](https://buildwithfern.com/docs/intro) to Fern's own documentation solution (#1871)
- [x] Move Fern documentation out of the core repository (#1871)

**Comment by dannysheridan** [comment]
@aevitas up to continue working through the generator READMEs next?

**Comment by aevitas** [comment]
Of course

**Comment by Leojack11** [comment]
Boom 💥
